language: node_js
node_js:
- '14.4.0'
install:
- npm install newman
- npm install -g newman-reporter-htmlextra
script:
- node_modules/.bin/newman run api-reqres-v3.json -e reqres.postman_environment.json -d reqres_datos.csv